### PR TITLE
improve CSV description and readme with template

### PR DESCRIPTION
**Pull request by dongwangdw**
Signed-off-by: dongdwdw <dongdwdw@cn.ibm.com>

### CODE REVIEW

**Comment by Lesiac** [comment]
@dongwangdw 
**REVIEW OF README FILE:**
**Line 5** change to: - The ibm-monitoring-grafana-operator installs the Grafana service. Use the Grafana service to present metrics dashboards that you can use for monitoring. You can also create your own metrics dashboards.

**Line 24** - In section , ## SecurityContextConstraints Requirements, **Replace this:**
- privileged SCC for operands
- restricted SCC for operator

**With this**: and include **WHICH** operands run under privileged?

The ibm-monitoring-grafana-operator supports running under the OpenShift Container Platform default restricted security context constraints. The <??**WHICH**??operands> run under privileged security constraints.
For more information about the OpenShift Container Platform Security Context Constraints, see [Managing Security Context Constraints](https://docs.openshift.com/container-platform/4.3/authentication/managing-security-context-constraints.html).

**Line 47**: Delete the "### Quick start guide" heading if you do not have any content for this section.

**Line 50**: Delete the ### Debugging guide heading if you do not have any content for this section.

**REVIEW OF CSV FILE:**
**Line 199:** In description: add the following statement in bold:
 **Important:** Do not install this operator directly. Only install this operator using the IBM Common Services Operator.
For more information about installing this operator and other Common Services operators, see Installer documentation. **Additionally, you can exit this panel and navigate to the IBM Common Services tile in OperatorHub to learn more about the operator.**

**Comment by dongwangdw** [comment]
@Lesiac 
>In README, Under section, SecurityContextConstraints Requirements, should the following statement be:
The grafana operator runs under privileged security constraints?

No, ```The ibm-monitoring-grafana-operator supports running under the OpenShift Container Platform default restricted security context constraints.```

Have I missed anything or missed your point? Please let me know. This is the text from the readme.

**Comment by Lesiac** [comment]
Sorry @dongwangdw my comment was not clear.  Do we need this statement-> "The grafana runs under privileged security constraints."  What is **grafana** referring to?  
You already have this statement for ibm-monitoring-grafana-operator ->"The ibm-monitoring-grafana-operator supports running under the OpenShift Container Platform default restricted security context constraints."

**Pull request merged**
